### ISSUE TITLE
Textarea Tagging System Doesn't Work on Google Search

### ISSUE THREAD

**Issue by Ponmo** [reworkd/tarsier#15]
Hey, I ran the same prompt as the example video. The new tagging system does not tag the textareas properly on the Google search page!

<img width="893" alt="Screen Shot 2023-11-27 at 9 16 33 PM" src="https://github.com/reworkd/tarsier/assets/77691125/e2b312b5-a755-4391-89f1-3dab2b387818">

**Comment by KhoomeiK** [comment]
Thanks for flagging this! My PR should fix this
https://github.com/reworkd/tarsier/pull/18

**Comment by shikunyu8** [comment]
I still see this issue after the PR - 'Google Search' and 'I'm Feeling Lucky' are not tagged.
